from django.urls import path
from rest_framework_simplejwt.views import TokenRefreshView
from . import views

urlpatterns = [
    path('register/', views.register_view, name='register'),
    path('login/', views.login_view, name='login'),
    path('password-reset/request/', views.password_reset_request_view, name='password_reset_request'),
    path('change-password/', views.change_password_view, name='change_password'),
    path('account/delete/', views.delete_account_view, name='delete_account'),
    path('profile/', views.profile_view, name='profile'),
    path('profile/upload-avatar/', views.upload_avatar_view, name='upload_avatar'),
    path('profile/confirm-avatar-upload/', views.confirm_avatar_upload_view, name='confirm_avatar_upload'),
    path('search/', views.search_view, name='search'),
    path('users/by-username/', views.user_by_username_view, name='user_by_username'),
    path('users/blocked/', views.blocked_users_list_view, name='blocked_users_list'),
    path('users/<int:user_id>/', views.user_detail_view, name='user_detail'),
    path('users/<int:user_id>/follow/', views.follow_user_view, name='follow_user'),
    path('users/<int:user_id>/block/', views.block_user_view, name='block_user'),
    path('users/<int:user_id>/follow-request/accept/', views.accept_follow_request_view, name='accept_follow_request'),
    path('users/<int:user_id>/follow-request/decline/', views.decline_follow_request_view, name='decline_follow_request'),
    path('users/<int:user_id>/followers/', views.user_followers_view, name='user_followers'),
    path('users/<int:user_id>/following/', views.user_following_view, name='user_following'),
    path('notifications/', views.notifications_view, name='notifications'),
    path('notifications/unread-count/', views.unread_notifications_count_view, name='unread_notifications_count'),
    path('notifications/<int:notification_id>/read/', views.mark_notification_read_view, name='mark_notification_read'),
    path('notifications/read-all/', views.mark_all_notifications_read_view, name='mark_all_notifications_read'),
    path('complices/', views.complices_view, name='complices'),
    path('followers/', views.followers_list_view, name='followers_list'),
    path('following/', views.following_list_view, name='following_list'),
    path('users/search/', views.users_search_view, name='users_search'),
    path('users/feed-suggestions/', views.feed_user_suggestions_view, name='feed_user_suggestions'),
    path('push-devices/register/', views.register_push_device_view, name='register_push_device'),
    path('push-devices/test/', views.test_push_device_view, name='test_push_device'),
    path('loyalty-cards/', views.LoyaltyCardListCreateView.as_view(), name='loyalty_card_list'),
    path('loyalty-cards/<int:pk>/', views.LoyaltyCardDetailView.as_view(), name='loyalty_card_detail'),
    path('loyalty-cards/<int:card_id>/barcode/', views.loyalty_card_barcode_view, name='loyalty_card_barcode'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
]

