"""
Taxonomie « parcours magasin » : parents = zones, feuilles = rayons assignables aux ingrédients.
Le matching par mots-clés est ordonné : la première correspondance l'emporte (phrases les plus
spécifiques en tête dans chaque groupe).
"""
from __future__ import annotations

import re
from typing import List, Optional, Sequence, Tuple

# (slug_parent, nom_parent, display_order_parent, [
#   (slug_enfant, nom_enfant, display_order_enfant, mots_clés),
# ])
SUPERMARKET_TREE: Sequence[Tuple[str, str, int, Sequence[Tuple[str, str, int, Sequence[str]]]]] = (
    (
        "pole_frais_marche",
        "Pôle Frais & Marché",
        10,
        (
            (
                "fruits_legumes",
                "Fruits et Légumes",
                11,
                (
                    "pomme de terre",
                    "patate douce",
                    "patate",
                    "tomate cerise",
                    "tomate",
                    "épinard",
                    "epinard",
                    "haricot vert",
                    "petit pois",
                    "pois chiche",
                    "pois cassé",
                    "chou kale",
                    "chou-fleur",
                    "chou de bruxelles",
                    "chou rouge",
                    "chou blanc",
                    "chou chinois",
                    "chou",
                    "salade iceberg",
                    "salade romaine",
                    "laitue",
                    "mâche",
                    "mache",
                    "roquette",
                    "mesclun",
                    "salade",
                    "courgette",
                    "aubergine",
                    "poivron",
                    "carotte",
                    "navet",
                    "radis",
                    "betterave",
                    "céleri-rave",
                    "celeri-rave",
                    "céleri branche",
                    "fenouil",
                    "asperge",
                    "artichaut",
                    "poireau",
                    "endive",
                    "brocoli",
                    "champignon",
                    "gingembre frais",
                    "gingembre",
                    "persil",
                    "basilic",
                    "coriandre",
                    "ciboulette",
                    "menthe",
                    "aneth",
                    "estragon",
                    "romarin",
                    "sauge",
                    "cerfeuil",
                    "bouquet garni",
                    "ail",
                    "échalote",
                    "echalote",
                    "oignon rouge",
                    "oignon jaune",
                    "oignon",
                    "citron vert",
                    "citron jaune",
                    "citron",
                    "orange sanguine",
                    "orange",
                    "pamplemousse",
                    "clémentine",
                    "clementine",
                    "mandarine",
                    "avocat",
                    "mangue",
                    "ananas",
                    "kiwi",
                    "raisin",
                    "cerise",
                    "fraise",
                    "framboise",
                    "myrtille",
                    "mûre",
                    "mure",
                    "melon",
                    "pastèque",
                    "pasteque",
                    "nectarine",
                    "brugnon",
                    "pêche",
                    "peche",
                    "abricot",
                    "prune",
                    "poire",
                    "pomme",
                    "banane",
                    "rhubarbe",
                    "courge butternut",
                    "butternut",
                    "potiron",
                    "courge",
                    "concombre",
                    "légume",
                    "legume",
                    "fruit",
                ),
            ),
            (
                "boulangerie_patisserie",
                "Boulangerie / Pâtisserie",
                12,
                (
                    "pain de mie",
                    "pain complet",
                    "pain aux céréales",
                    "pain aux cereales",
                    "focaccia",
                    "ciabatta",
                    "brioche",
                    "viennoiserie",
                    "croissant",
                    "pain au chocolat",
                    "chouquette",
                    "éclair",
                    "eclair",
                    "tarte aux pommes",
                    "tartelette",
                    "millefeuille",
                    "gâteau",
                    "gateau",
                    "tarte",
                    "pizza crue",
                    "pâte à pizza",
                    "pate a pizza",
                    "pâte brisée",
                    "pate brisee",
                    "pâte feuilletée",
                    "pate feuilletee",
                    "feuilles de brick",
                    "feuille de brick",
                    "pizza",
                    "baguette",
                    "pain",
                ),
            ),
            (
                "boucherie_charcuterie_traiteur",
                "Boucherie / Charcuterie / Traiteur",
                13,
                (
                    "côte d'agneau",
                    "cote d'agneau",
                    "gigot",
                    "épaule d'agneau",
                    "escalope de veau",
                    "veau",
                    "bifteck",
                    "entrecôte",
                    "entrecote",
                    "rumsteck",
                    "bavette",
                    "onglet",
                    "steak",
                    "côte de boeuf",
                    "cote de boeuf",
                    "boeuf",
                    "bœuf",
                    "porc",
                    "échine",
                    "echine",
                    "filet mignon",
                    "carré de porc",
                    "jambon sec",
                    "saucisse de toulouse",
                    "merguez",
                    "chipolata",
                    "boudin",
                    "andouillette",
                    "rôti de porc",
                    "roti de porc",
                    "rôti de veau",
                    "roti de veau",
                    "rôti de boeuf",
                    "roti de boeuf",
                    "poulet entier",
                    "blanc de poulet",
                    "cuisse de poulet",
                    "aile de poulet",
                    "pilon",
                    "poulet",
                    "dinde",
                    "canard",
                    "lapin",
                    "veau haché",
                    "steak haché",
                    "steak hache",
                    "viande hachée",
                    "viande hachee",
                    "viande",
                    "charcuterie traiteur",
                    "plat cuisiné frais",
                    "plat cuisine frais",
                    "quiche",
                    "tarte salée",
                    "tarte salee",
                    "feuilleté",
                    "feuillete",
                    "cordon bleu",
                    "nugget",
                    "côtelette",
                    "cotelette",
                ),
            ),
            (
                "poissonnerie",
                "Poissonnerie",
                14,
                (
                    "fruit de mer",
                    "fruits de mer",
                    "noix de saint-jacques",
                    "saint-jacques",
                    "langoustine",
                    "homard",
                    "araignée de mer",
                    "araignee de mer",
                    "bulot",
                    "bigorneau",
                    "huître",
                    "huitre",
                    "moule",
                    "palourde",
                    "coque",
                    "crevette rose",
                    "crevette grise",
                    "crevette",
                    "crabe",
                    "poulpe",
                    "calmar",
                    "seiche",
                    "encornet",
                    "pieuvre",
                    "sardine",
                    "maquereau",
                    "hareng",
                    "anchois",
                    "saint-pierre",
                    "bar de ligne",
                    "loup de mer",
                    "daurade",
                    "dorade",
                    "bar",
                    "sole",
                    "turbot",
                    "cabillaud",
                    "colin",
                    "lieu",
                    "merlu",
                    "raie",
                    "lotte",
                    "sandre",
                    "brochet",
                    "truite",
                    "omble",
                    "saumon fumé",
                    "saumon fume",
                    "saumon frais",
                    "saumon",
                    "thon",
                    "espadon",
                    "poisson fumé",
                    "poisson fume",
                    "poisson pané",
                    "poisson pane",
                    "poisson",
                ),
            ),
        ),
    ),
    (
        "rayon_frais_libre_service",
        "Rayon Frais Libre-Service",
        20,
        (
            (
                "cremerie_oeufs",
                "Crémerie & Œufs",
                21,
                (
                    "crème liquide",
                    "creme liquide",
                    "crème entière",
                    "creme entiere",
                    "crème fraîche",
                    "crème fraiche",
                    "creme fraiche",
                    "crème",
                    "creme",
                    "beurre demi-sel",
                    "beurre salé",
                    "beurre sale",
                    "beurre",
                    "mascarpone",
                    "œuf",
                    "oeuf",
                    "oeufs",
                    "blanc d'oeuf",
                    "jaune d'oeuf",
                    "lait cru",
                    "lait frais",
                    "lait entier",
                    "lait demi-écrémé",
                    "lait demi-ecreme",
                    "lait écrémé",
                    "lait ecreme",
                    "lait de vache",
                ),
            ),
            (
                "produits_laitiers_ultra_frais",
                "Produits Laitiers / Ultra-frais",
                22,
                (
                    "fromage à raclette",
                    "fromage a raclette",
                    "fromage à tartiner",
                    "fromage a tartiner",
                    "fromage râpé",
                    "fromage rape",
                    "fromage de chèvre",
                    "fromage de chevre",
                    "fromage bleu",
                    "camembert",
                    "brie",
                    "comté",
                    "comte",
                    "emmental",
                    "gruyère",
                    "gruyere",
                    "parmesan",
                    "mozzarella",
                    "ricotta",
                    "feta",
                    "féta",
                    "chèvre frais",
                    "chevre frais",
                    "fromage blanc",
                    "faisselle",
                    "petit-suisse",
                    "skyr",
                    "yaourt grec",
                    "yaourt à boire",
                    "yaourt a boire",
                    "yaourt",
                    "yogourt",
                    "yoghurt",
                    "danette",
                    "crème dessert",
                    "creme dessert",
                    "riz au lait",
                    "flan aux oeufs",
                    "panna cotta",
                    "dessert lacté",
                    "dessert lacte",
                    "fromage",
                ),
            ),
            (
                "charcuterie_libre_service",
                "Charcuterie libre-service",
                23,
                (
                    "lardons fumés",
                    "lardons fumes",
                    "lardons nature",
                    "lardons",
                    "dés de jambon",
                    "des de jambon",
                    "jambon cuit",
                    "jambon blanc",
                    "jambon de paris",
                    "jambon",
                    "bacon",
                    "poitrine fumée",
                    "poitrine fumee",
                    "pancetta",
                    "mortadelle",
                    "rosbeef",
                    "pastrami",
                ),
            ),
        ),
    ),
    (
        "epicerie_seche",
        "Épicerie sèche",
        30,
        (
            (
                "epicerie_salee",
                "Épicerie Salée",
                31,
                (
                    "lait de coco",
                    "tofu",
                    "tempeh",
                    "miso",
                    "houmous",
                    "hummus",
                    "pesto",
                    "tapenade",
                    "lait en poudre",
                    "lait concentré",
                    "lait concentre",
                    "lait d'amande",
                    "lait d amande",
                    "lait de soja",
                    "lait d'avoine",
                    "lait d avoine",
                    "sauce soja",
                    "sauce teriyaki",
                    "sauce nuoc-mâm",
                    "sauce nuoc mam",
                    "sauce poisson",
                    "sauce barbecue",
                    "ketchup",
                    "mayonnaise",
                    "moutarde",
                    "vinaigre balsamique",
                    "vinaigre de cidre",
                    "vinaigre",
                    "huile de sésame",
                    "huile de sesame",
                    "huile d'olive",
                    "huile d olive",
                    "huile de tournesol",
                    "huile de colza",
                    "huile",
                    "bouillon cube",
                    "bouillon",
                    "fond de veau",
                    "fumet de poisson",
                    "sauce tomate",
                    "coulis",
                    "concentré de tomate",
                    "concentre de tomate",
                    "double concentré",
                    "double concentre",
                    "tomate pelée",
                    "tomate pelee",
                    "haricot blanc",
                    "haricot rouge",
                    "haricot",
                    "lentille corail",
                    "lentille verte",
                    "lentille",
                    "pois chiche sec",
                    "flageolet",
                    "maïs en conserve",
                    "mais en conserve",
                    "maïs",
                    "mais",
                    "olive noire",
                    "olive verte",
                    "olive",
                    "cornichon",
                    "câpre",
                    "capre",
                    "anchois en boîte",
                    "thon en boîte",
                    "thon en boite",
                    "sardine en boîte",
                    "sardine en boite",
                    "rillettes",
                    "terrine",
                    "saucisson sec",
                    "chorizo sec",
                    "jambon cru",
                    "speck",
                    "chips",
                    "cacahuète",
                    "cacahuete",
                    "cacahuètes",
                    "cacahuetes",
                    "apéritif",
                    "aperitif",
                    "biscuit apéro",
                    "biscuit apero",
                    "cracker",
                    "tortilla",
                    "nacho",
                    "pop-corn",
                    "pop corn",
                    "sel fin",
                    "gros sel",
                    "fleur de sel",
                    "sel",
                    "poivre noir",
                    "poivre blanc",
                    "poivre",
                    "paprika",
                    "cumin",
                    "curry",
                    "curcuma",
                    "gingembre en poudre",
                    "cannelle",
                    "muscade",
                    "clou de girofle",
                    "laurier",
                    "thym séché",
                    "thym seche",
                    "origan",
                    "herbes de provence",
                    "piment d'espelette",
                    "piment",
                    "tabasco",
                    "sriracha",
                    "worcestershire",
                    "sauce hollandaise",
                    "béchamel",
                    "bechamel",
                    "couscous",
                    "boulgour",
                    "semoule",
                    "quinoa",
                    "riz basmati",
                    "riz arborio",
                    "riz rond",
                    "riz complet",
                    "riz",
                    "pâtes",
                    "pates",
                    "lasagne",
                    "cannelloni",
                    "nouilles",
                    "vermicelle",
                    "spaghetti",
                    "penne",
                    "tagliatelle",
                    "gnocchi secs",
                    "gnocchi sec",
                    "gnocchi",
                    "farine complète",
                    "farine complete",
                    "farine de blé",
                    "farine de ble",
                    "farine",
                    "levure chimique",
                    "levure de boulanger",
                    "levure",
                    "bicarbonate",
                    "levure du malt",
                    "fécule",
                    "fecule",
                    "maïzena",
                    "maizena",
                    "chapelure",
                ),
            ),
            (
                "epicerie_sucree",
                "Épicerie Sucrée",
                32,
                (
                    "chocolat noir",
                    "chocolat au lait",
                    "chocolat blanc",
                    "pépites de chocolat",
                    "pepites de chocolat",
                    "cacao en poudre",
                    "chocolat",
                    "pâte à tartiner",
                    "pate a tartiner",
                    "nutella",
                    "confiture",
                    "miel",
                    "sirop d'érable",
                    "sirop d erable",
                    "sirop d'agave",
                    "sirop d agave",
                    "extrait de vanille",
                    "vanille",
                    "cassonade",
                    "vergeoise",
                    "sucre glace",
                    "sucre vanillé",
                    "sucre vanille",
                    "sucre roux",
                    "sucre semoule",
                    "sucre",
                    "farine de coco",
                    "noix de coco râpée",
                    "noix de coco rapee",
                    "noix de pécan",
                    "noix de pecan",
                    "noisette",
                    "noix",
                    "amande",
                    "pistache",
                    "raisin sec",
                    "datte",
                    "figue sèche",
                    "figue seche",
                    "pruneau",
                    "abricot sec",
                    "biscuit sec",
                    "biscuit",
                    "cookie",
                    "galette",
                    "madeleine",
                    "barre céréales",
                    "barre cereales",
                    "céréale petit-déjeuner",
                    "cereale petit-dejeuner",
                    "café moulu",
                    "cafe moulu",
                    "café en grain",
                    "cafe en grain",
                    "café soluble",
                    "cafe soluble",
                    "café",
                    "cafe",
                    "thé vert",
                    "the vert",
                    "thé noir",
                    "the noir",
                    "infusion",
                    "thé",
                    "the",
                    "tisane",
                ),
            ),
        ),
    ),
    (
        "liquides",
        "Les Liquides",
        40,
        (
            (
                "eaux_sodas",
                "Eaux et Sodas",
                41,
                (
                    "eau gazeuse",
                    "eau pétillante",
                    "eau petillante",
                    "eau minérale",
                    "eau minerale",
                    "eau plate",
                    "eau",
                    "soda",
                    "cola",
                    "limonade",
                    "sprite",
                    "fanta",
                    "orangina",
                    "schweppes",
                    "tonic",
                    "ginger ale",
                    "ice tea",
                    "thé glacé",
                    "the glace",
                    "jus de pomme",
                    "jus d'orange",
                    "jus d orange",
                    "jus de raisin",
                    "jus de tomate",
                    "jus en brique",
                    "nectar",
                    "sirop à diluer",
                    "sirop a diluer",
                    "lait",
                    "lait uht",
                    "lait longue conservation",
                    "boisson végétale",
                    "boisson vegetale",
                    "boisson",
                ),
            ),
            (
                "cave",
                "Cave",
                42,
                (
                    "champagne",
                    "crémant",
                    "cremant",
                    "mousseux",
                    "cidre brut",
                    "cidre",
                    "vin blanc",
                    "vin rouge",
                    "vin rosé",
                    "vin rose",
                    "vin",
                    "porto",
                    "sherry",
                    "xérès",
                    "xeres",
                    "bière",
                    "biere",
                    "whisky",
                    "whiskey",
                    "vodka",
                    "rhum",
                    "gin",
                    "tequila",
                    "cognac",
                    "armagnac",
                    "liqueur",
                    "apéritif alcoolisé",
                    "aperitif alcoolise",
                    "alcool",
                ),
            ),
        ),
    ),
    (
        "surgeles_section",
        "Les Surgelés",
        50,
        (
            (
                "surgeles",
                "Surgelés",
                51,
                (
                    "glace",
                    "sorbet",
                    "bâtonnet glacé",
                    "batonnet glace",
                    "surgelé",
                    "surgele",
                    "congelé",
                    "congele",
                    "légumes surgelés",
                    "legumes surgeles",
                    "épinards surgelés",
                    "epinards surgeles",
                    "petits pois surgelés",
                    "petits pois surgeles",
                    "haricots surgelés",
                    "haricots surgeles",
                    "frites surgelées",
                    "frites surgelees",
                    "frites",
                    "pizza surgelée",
                    "pizza surgelee",
                    "lasagne surgelée",
                    "lasagne surgelee",
                    "plats surgelés",
                    "plats surgeles",
                    "poisson surgelé",
                    "poisson surgele",
                    "viande surgelée",
                    "viande surgelee",
                    "fruits rouges surgelés",
                    "fruits rouges surgeles",
                ),
            ),
        ),
    ),
    (
        "non_alimentaire",
        "Non-alimentaire",
        60,
        (
            (
                "dph",
                "DPH (Droguerie, Parfumerie, Hygiène)",
                61,
                (
                    "lessive",
                    "adoucissant",
                    "lave-vaisselle",
                    "lave vaisselle",
                    "liquide vaisselle",
                    "pastille lave-vaisselle",
                    "éponge",
                    "eponge",
                    "serpillière",
                    "serpilliere",
                    "chiffon",
                    "nettoyant",
                    "détergent",
                    "detergent",
                    "javel",
                    "eau de javel",
                    "désinfectant",
                    "desinfectant",
                    "papier toilette",
                    "papier essuie-tout",
                    "papier essuie tout",
                    "mouchoir",
                    "cotons",
                    "coton-tige",
                    "coton tige",
                    "shampoing",
                    "après-shampoing",
                    "apres-shampoing",
                    "gel douche",
                    "savon",
                    "dentifrice",
                    "brosse à dents",
                    "brosse a dents",
                    "déodorant",
                    "deodorant",
                    "crème hydratante",
                    "creme hydratante",
                    "rasoir",
                    "lame de rasoir",
                ),
            ),
            (
                "bebe",
                "Bébé",
                62,
                (
                    "couche",
                    "couches",
                    "lingette bébé",
                    "lingette bebe",
                    "biberon",
                    "tétine",
                    "tetine",
                    "petit pot bébé",
                    "petit pot bebe",
                    "purée bébé",
                    "puree bebe",
                    "lait infantile",
                    "lait 1er âge",
                    "lait 1er age",
                    "lait 2e âge",
                    "lait 2e age",
                ),
            ),
            (
                "bazar_textile",
                "Bazar / Textile",
                63,
                (
                    "papier cadeau",
                    "ruban",
                    "batterie",
                    "pile",
                    "ampoule",
                    "sac poubelle",
                    "film alimentaire",
                    "papier aluminium",
                    "papier sulfurisé",
                    "papier sulfurise",
                    "ustensile",
                    "poêle",
                    "poele",
                    "casserole",
                    "couteau de cuisine",
                    "planche à découper",
                    "planche a decouper",
                    "livre",
                    "cahier",
                    "stylo",
                    "vêtement",
                    "vetement",
                    "chaussette",
                    "t-shirt",
                    "serviette",
                ),
            ),
        ),
    ),
    (
        "divers",
        "Divers",
        90,
        (
            (
                "autres",
                "Autres",
                91,
                (),
            ),
        ),
    ),
)


def _flatten_keyword_rules() -> List[Tuple[str, str]]:
    """(slug, keyword) triés par longueur de keyword décroissante pour prioriser les expressions."""
    pairs: List[Tuple[str, str]] = []
    for _ps, _pn, _po, children in SUPERMARKET_TREE:
        for slug, _name, _co, keywords in children:
            for kw in keywords:
                pairs.append((slug, kw))
    pairs.sort(key=lambda x: len(x[1]), reverse=True)
    return pairs


FLAT_KEYWORD_RULES: List[Tuple[str, str]] = _flatten_keyword_rules()

# Anciennes catégories (avant refonte) → slug feuille par défaut ; le script de rattrapage
# ré-applique ensuite les mots-clés pour affiner (ex. poisson).
LEGACY_CATEGORY_NAME_TO_LEAF_SLUG = {
    "Fruits": "fruits_legumes",
    "Légumes": "fruits_legumes",
    "Viandes & Poissons": "boucherie_charcuterie_traiteur",
    "Produits laitiers": "produits_laitiers_ultra_frais",
    "Pain & Pâtisserie": "boulangerie_patisserie",
    "Épicerie": "epicerie_salee",
    "Autres": "autres",
}


_MATCH_STOPWORDS = frozenset(
    {"de", "des", "du", "d", "a", "à", "au", "aux", "et", "en", "la", "le", "les", "un", "une"}
)


def _normalize_match_text(name: str) -> str:
    n = name.lower().strip()
    n = n.replace("œ", "oe").replace("æ", "ae")
    return re.sub(r"\s+", " ", n)


def _keyword_matches(name_lower: str, kw: str) -> bool:
    """
    Match exact ou pluriel FR simple (s/x optionnel).
    Évite les faux positifs type « lait » dans « laitue » via limites de mot.
    """
    if " " not in kw:
        return (
            re.search(
                r"(?<!\w)" + re.escape(kw) + r"(?:s|x)?(?!\w)",
                name_lower,
                flags=re.UNICODE,
            )
            is not None
        )

    parts: List[str] = []
    for w in kw.split():
        if w in _MATCH_STOPWORDS or len(w) <= 2:
            parts.append(re.escape(w))
        else:
            parts.append(re.escape(w) + r"(?:s|x)?")
    pattern = r"(?<!\w)" + r"\s+".join(parts) + r"(?!\w)"
    return re.search(pattern, name_lower, flags=re.UNICODE) is not None


def match_leaf_slug_from_name(name: str) -> Optional[str]:
    """
    Retourne le slug de la feuille si un mot-clé matche, sinon None.
    """
    if not name or not name.strip():
        return None
    n = _normalize_match_text(name)
    for slug, kw in FLAT_KEYWORD_RULES:
        if _keyword_matches(n, kw):
            return slug
    return None


def all_leaf_slugs() -> List[str]:
    out: List[str] = []
    for _ps, _pn, _po, children in SUPERMARKET_TREE:
        for slug, _name, _co, _kws in children:
            out.append(slug)
    return out
