# Generated by Django 5.2.8 on 2025-11-11 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('follow', 'Nouveau complice'), ('recipe_reminder', 'Rappel de recette'), ('recipe_shared', 'Recette partagée'), ('achievement', 'Nouveau succès'), ('meal_invitation', 'Invitation à un repas')], max_length=50, verbose_name='Type de notification'),
        ),
    ]
