# Generated by Django 5.2.8 on 2025-11-12 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('follow', 'Nouveau complice'), ('recipe_reminder', 'Rappel de recette'), ('recipe_shared', 'Recette partagée'), ('achievement', 'Nouveau succès'), ('meal_invitation', 'Invitation à un repas'), ('photo_during_cooking', 'Photo pendant la cuisine'), ('photo_after_cooking', 'Photo après la cuisine'), ('photo_at_meal_time', "Photo à l'heure du repas")], max_length=50, verbose_name='Type de notification'),
        ),
    ]
