# Generated by Django 5.2.8 on 2025-11-19 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_shopping_list_days',
            field=models.IntegerField(default=7, help_text='Nombre de jours par défaut pour la liste de courses'),
        ),
    ]
