# Generated by Django 5.2.8 on 2025-11-19 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_default_shopping_list_days'),
        ('recipes', '0022_recipe_import_source_url_recipe_is_public_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_recipes',
            field=models.ManyToManyField(blank=True, help_text="Recettes favorites de l'utilisateur", related_name='favorited_by', to='recipes.recipe'),
        ),
    ]
