# Generated by Django 5.2.8 on 2026-02-28 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_post_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID du post lié'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('follow', 'Nouvel ami'), ('recipe_reminder', 'Rappel de recette'), ('recipe_shared', 'Recette partagée'), ('achievement', 'Nouveau succès'), ('meal_invitation', 'Invitation à un repas'), ('photo_during_cooking', 'Photo pendant la cuisine'), ('photo_after_cooking', 'Photo après la cuisine'), ('photo_at_meal_time', "Photo à l'heure du repas"), ('post_miam', 'Miam sur votre post'), ('post_comment', 'Commentaire sur votre post'), ('post_comment_mention', 'Vous êtes mentionné dans un commentaire')], max_length=50, verbose_name='Type de notification'),
        ),
    ]
