# Generated by Django 5.2.8 on 2026-03-29 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_user_regimes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_vegetarian',
            field=models.BooleanField(default=False, help_text='Régime végétarien (repérage viande/poisson côté recettes, en complément des listes).'),
        ),
    ]
