# Generated by Django 5.2.8 on 2025-11-06 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealplan',
            name='meal_type',
            field=models.CharField(choices=[('cantine', 'Cantine'), ('takeaway', 'À emporter'), ('recipe', 'Recette'), ('unknown', 'Je ne sais pas')], max_length=20),
        ),
    ]
