# Generated by Django 5.2.8 on 2025-11-07 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_mealplan_meal_type'),
    ]

    operations = [
        # Installer l'extension pg_trgm si elle n'existe pas déjà
        migrations.RunSQL(
            sql="CREATE EXTENSION IF NOT EXISTS pg_trgm;",
            reverse_sql="DROP EXTENSION IF EXISTS pg_trgm;"
        ),
        # Index GIN pour Full-Text Search sur title et description
        migrations.RunSQL(
            sql="""
                CREATE INDEX IF NOT EXISTS recipes_recipe_title_description_gin_idx 
                ON recipes_recipe 
                USING gin(to_tsvector('french', COALESCE(title, '') || ' ' || COALESCE(description, '')));
            """,
            reverse_sql="DROP INDEX IF EXISTS recipes_recipe_title_description_gin_idx;"
        ),
        # Index GIN pour trigram similarity sur title
        migrations.RunSQL(
            sql="""
                CREATE INDEX IF NOT EXISTS recipes_recipe_title_trgm_idx 
                ON recipes_recipe 
                USING gin(title gin_trgm_ops);
            """,
            reverse_sql="DROP INDEX IF EXISTS recipes_recipe_title_trgm_idx;"
        ),
        # Index GIN pour trigram similarity sur description
        migrations.RunSQL(
            sql="""
                CREATE INDEX IF NOT EXISTS recipes_recipe_description_trgm_idx 
                ON recipes_recipe 
                USING gin(description gin_trgm_ops);
            """,
            reverse_sql="DROP INDEX IF EXISTS recipes_recipe_description_trgm_idx;"
        ),
    ]
