# Generated by Django 5.2.8 on 2025-11-07 00:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_add_search_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_meal_plans', to=settings.AUTH_USER_MODEL, verbose_name='Partagé avec'),
        ),
    ]
