# Generated by Django 5.2.8 on 2025-11-11 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_mealplan_shared_with'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MealInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Acceptée'), ('declined', 'Refusée')], default='pending', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
            ],
            options={
                'verbose_name': 'Invitation à un repas',
                'verbose_name_plural': 'Invitations à des repas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='mealplan',
            index=models.Index(fields=['user', 'date'], name='mealplan_user_date_idx'),
        ),
        migrations.AddField(
            model_name='mealinvitation',
            name='invitee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_meal_invitations', to=settings.AUTH_USER_MODEL, verbose_name='Invité'),
        ),
        migrations.AddField(
            model_name='mealinvitation',
            name='inviter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_meal_invitations', to=settings.AUTH_USER_MODEL, verbose_name='Inviteur'),
        ),
        migrations.AddField(
            model_name='mealinvitation',
            name='meal_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='recipes.mealplan', verbose_name='Repas planifié'),
        ),
        migrations.AlterUniqueTogether(
            name='mealinvitation',
            unique_together={('invitee', 'meal_plan')},
        ),
    ]
