# Generated by Django 5.2.8 on 2025-11-11 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_mealinvitation_mealplan_mealplan_user_date_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealplan',
            name='shared_with',
        ),
    ]
