# Generated by Django 5.2.8 on 2025-11-11 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_remove_mealplan_shared_with'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='steps_summary',
            field=models.TextField(blank=True, help_text='Résumé des étapes de préparation'),
        ),
    ]
