# Generated by Django 5.2.8 on 2025-11-11 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_recipe_steps_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='tip',
            field=models.TextField(blank=True, help_text='Astuce ou conseil pour cette étape'),
        ),
        migrations.CreateModel(
            name='StepIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(choices=[('g', 'Grammes'), ('kg', 'Kilogrammes'), ('ml', 'Millilitres'), ('l', 'Litres'), ('tsp', 'Cuillère à café'), ('tbsp', 'Cuillère à soupe'), ('cup', 'Tasse'), ('piece', 'Pièce(s)'), ('pinch', 'Pincée(s)'), ('clove', 'Gousse(s)')], default='g', max_length=20)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.ingredient')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_ingredients', to='recipes.step')),
            ],
            options={
                'ordering': ['ingredient__name'],
                'unique_together': {('step', 'ingredient')},
            },
        ),
        migrations.AddField(
            model_name='step',
            name='ingredients',
            field=models.ManyToManyField(blank=True, related_name='steps', through='recipes.StepIngredient', to='recipes.ingredient'),
        ),
    ]
