# Generated by Django 5.2.8 on 2025-11-11 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_step_tip_stepingredient_step_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='title',
            field=models.CharField(blank=True, help_text="Titre court de l'étape", max_length=200),
        ),
    ]
