# Generated by Django 5.2.8 on 2025-11-11 18:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_cookingprogress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cookingprogress',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'in_progress')), fields=('user', 'recipe', 'meal_plan', 'status'), name='unique_in_progress_per_recipe_mealplan'),
        ),
    ]
