# Generated by Django 5.2.8 on 2025-11-11 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_cookingprogress_unique_in_progress_per_recipe_mealplan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='has_timer',
            field=models.BooleanField(default=False, help_text='Cette étape nécessite un minuteur'),
        ),
        migrations.AddField(
            model_name='step',
            name='timer_duration',
            field=models.IntegerField(blank=True, help_text='Durée par défaut du minuteur en minutes', null=True),
        ),
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_minutes', models.IntegerField(help_text='Durée totale du minuteur en minutes')),
                ('remaining_seconds', models.IntegerField(help_text='Secondes restantes')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text="Date et heure d'expiration")),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cooking_progress', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timers', to='recipes.cookingprogress')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_timers', to='recipes.recipe')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timers', to='recipes.step')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_timers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['expires_at'],
                'indexes': [models.Index(fields=['user', 'is_completed'], name='timer_user_completed_idx'), models.Index(fields=['expires_at'], name='timer_expires_at_idx')],
            },
        ),
    ]
