# Generated by Django 5.2.8 on 2025-11-12 23:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_step_has_timer_step_timer_duration_timer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, help_text='Commentaire du post')),
                ('is_published', models.BooleanField(default=False, help_text='Le post est publié')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cooking_progress', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='recipes.cookingprogress')),
                ('meal_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='recipes.mealplan')),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='recipes.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_type', models.CharField(choices=[('during_cooking', 'Pendant la cuisine'), ('after_cooking', 'Après la cuisine'), ('at_meal_time', "À l'heure du repas"), ('spontaneous', 'Spontanée')], help_text='Type de photo', max_length=20)),
                ('image_url', models.URLField(help_text='URL de la photo dans S3')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='recipes.post')),
                ('step', models.ForeignKey(blank=True, help_text='Étape associée si photo spontanée', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_photos', to='recipes.step')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['user', 'is_published'], name='post_user_published_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['recipe'], name='post_recipe_idx'),
        ),
        migrations.AddConstraint(
            model_name='postphoto',
            constraint=models.UniqueConstraint(condition=models.Q(('photo_type__in', ['during_cooking', 'after_cooking', 'at_meal_time'])), fields=('post', 'photo_type'), name='unique_photo_type_per_post'),
        ),
    ]
