# Generated by Django 5.2.8 on 2025-11-13 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_post_postphoto_post_post_user_published_idx_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='postphoto',
            name='unique_photo_type_per_post',
        ),
        migrations.AddField(
            model_name='postphoto',
            name='meal_plan',
            field=models.ForeignKey(blank=True, help_text='Meal plan associé (avant publication)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='draft_photos', to='recipes.mealplan'),
        ),
        migrations.AlterField(
            model_name='postphoto',
            name='post',
            field=models.ForeignKey(blank=True, help_text='Post associé (null si pas encore publié)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='recipes.post'),
        ),
        migrations.AddConstraint(
            model_name='postphoto',
            constraint=models.UniqueConstraint(condition=models.Q(('photo_type__in', ['during_cooking', 'after_cooking', 'at_meal_time']), ('post__isnull', False)), fields=('post', 'photo_type'), name='unique_photo_type_per_post'),
        ),
        migrations.AddConstraint(
            model_name='postphoto',
            constraint=models.UniqueConstraint(condition=models.Q(('photo_type__in', ['during_cooking', 'after_cooking', 'at_meal_time']), ('meal_plan__isnull', False)), fields=('meal_plan', 'photo_type'), name='unique_photo_type_per_meal_plan'),
        ),
    ]
