# Generated by Django 5.2.8 on 2025-11-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_remove_postphoto_unique_photo_type_per_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postphoto',
            name='photo_type',
            field=models.CharField(choices=[('during_cooking', 'Pendant la cuisine'), ('after_cooking', 'Après la cuisine'), ('at_meal_time', "À l'heure du repas"), ('spontaneous', 'Spontanée'), ('imported_after_cooking', 'Importée après la recette')], help_text='Type de photo', max_length=25),
        ),
    ]
