# Generated by Django 5.2.8 on 2025-11-14 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_alter_postphoto_photo_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postphoto',
            name='image_url',
        ),
        migrations.AddField(
            model_name='postphoto',
            name='image_path',
            field=models.CharField(help_text='Chemin relatif de la photo dans S3 (ex: meal_plans/70/6096a520a71247229f1cae315fc2bd84.jpg)', max_length=500),
        ),
    ]
