# Generated by Django 5.2.8 on 2025-11-14 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0016_replace_image_url_with_image_path'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postphoto',
            options={'ordering': ['order', 'created_at']},
        ),
        migrations.AddField(
            model_name='postphoto',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text="Ordre d'affichage dans le post (0 = non ordonné, utilise created_at)"),
        ),
    ]
