# Generated by Django 5.2.8 on 2025-11-19 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0018_postcookie'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Nom de la liste (optionnel, par défaut date de création)', max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Liste active (une seule liste active par utilisateur à la fois)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meal_plans', models.ManyToManyField(help_text='Repas planifiés inclus dans cette liste', related_name='shopping_lists', to='recipes.mealplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShoppingListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('to_buy', 'À acheter'), ('in_pantry', 'Dans les placards'), ('purchased', 'Acheté')], default='to_buy', max_length=20)),
                ('pantry_quantity', models.DecimalField(decimal_places=2, default=0, help_text='Quantité déjà disponible dans les placards', max_digits=10)),
                ('pantry_unit', models.CharField(blank=True, help_text='Unité de la quantité dans les placards', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_list_items', to='recipes.ingredient')),
                ('shopping_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='recipes.shoppinglist')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='shoppinglist',
            index=models.Index(fields=['user', 'is_active'], name='shoppinglist_user_active_idx'),
        ),
        migrations.AddIndex(
            model_name='shoppinglistitem',
            index=models.Index(fields=['shopping_list', 'status'], name='shoplistitem_status_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='shoppinglistitem',
            unique_together={('shopping_list', 'ingredient')},
        ),
    ]
