# Generated by Django 5.2.8 on 2025-11-19 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0019_shoppinglist_shoppinglistitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('display_order', models.IntegerField(default=0, help_text="Ordre d'affichage dans les listes")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='ingredient',
            name='category',
            field=models.ForeignKey(blank=True, help_text="Catégorie de l'ingrédient", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredients', to='recipes.category'),
        ),
    ]
