# Generated by Django 5.2.8 on 2025-11-19 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0020_category_ingredient_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Liste archivée'),
        ),
    ]
