# Generated by Django 5.2.8 on 2025-11-19 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0021_shoppinglist_is_archived'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='import_source_url',
            field=models.URLField(blank=True, help_text='URL source si la recette a été importée', null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Recette publique ou privée'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='source_type',
            field=models.CharField(choices=[('user_created', "Créée par l'utilisateur"), ('imported', 'Importée'), ('system', 'Système')], default='user_created', help_text='Type de source de la recette', max_length=20),
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom de la collection', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description de la collection')),
                ('is_public', models.BooleanField(default=True, help_text='Collection publique ou privée')),
                ('is_collaborative', models.BooleanField(default=False, help_text='Mode collaboratif activé')),
                ('cover_image_path', models.CharField(blank=True, help_text="Chemin relatif de l'image de couverture dans S3", max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(help_text='Propriétaire de la collection', on_delete=django.db.models.deletion.CASCADE, related_name='collections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CollectionRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(help_text='Utilisateur qui a ajouté la recette à la collection', on_delete=django.db.models.deletion.CASCADE, related_name='added_collection_recipes', to=settings.AUTH_USER_MODEL)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_recipes', to='recipes.collection')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_recipes', to='recipes.recipe')),
            ],
            options={
                'ordering': ['-added_at'],
            },
        ),
        migrations.AddField(
            model_name='collection',
            name='recipes',
            field=models.ManyToManyField(blank=True, related_name='collections', through='recipes.CollectionRecipe', to='recipes.recipe'),
        ),
        migrations.CreateModel(
            name='CollectionMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Propriétaire'), ('collaborator', 'Collaborateur')], default='collaborator', help_text='Rôle dans la collection', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='recipes.collection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['joined_at'],
                'unique_together': {('collection', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='collectionrecipe',
            index=models.Index(fields=['collection', 'recipe'], name='collrecipe_coll_recipe_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='collectionrecipe',
            unique_together={('collection', 'recipe')},
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['owner', 'is_public'], name='collection_owner_public_idx'),
        ),
    ]
