# Generated by Django 5.2.8 on 2025-11-20 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0022_recipe_import_source_url_recipe_is_public_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='embedding',
            field=models.JSONField(blank=True, help_text="Vecteur d'embedding pour la recherche sémantique", null=True),
        ),
    ]
