# Generated by Django 5.2.8 on 2025-11-20 20:34

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0024_enable_pgvector'),
    ]

    operations = [
        # Étape 1 : Supprimer l'ancien champ JSONB
        migrations.RemoveField(
            model_name='ingredient',
            name='embedding',
        ),
        # Étape 2 : Créer le nouveau champ VectorField
        migrations.AddField(
            model_name='ingredient',
            name='embedding',
            field=pgvector.django.vector.VectorField(
                blank=True,
                dimensions=384,
                help_text="Vecteur d'embedding pour la recherche sémantique",
                null=True
            ),
        ),
    ]
