# Generated by Django 5.2.8 on 2025-11-21 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0028_recipe_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeimportrequest',
            name='task_id',
            field=models.CharField(blank=True, help_text='ID de la tâche Celery associée', max_length=255, null=True),
        ),
    ]
