# Generated by Django 5.2.8 on 2025-11-23 15:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0030_add_post_performance_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='is_cooked',
            field=models.BooleanField(default=False, help_text='Le plat a été cuisiné'),
        ),
        migrations.AddIndex(
            model_name='mealplan',
            index=models.Index(fields=['user', 'is_cooked'], name='mealplan_user_cooked_idx'),
        ),
    ]
