# Generated by Django 5.2.8 on 2025-11-29 20:46

import django.db.models.deletion
from django.db import migrations, models


def migrate_existing_meal_plans(apps, schema_editor):
    """Migrer les MealPlan existants avec recipe vers MealPlanRecipe"""
    MealPlan = apps.get_model('recipes', 'MealPlan')
    MealPlanRecipe = apps.get_model('recipes', 'MealPlanRecipe')
    
    # Pour chaque MealPlan qui a un recipe, créer un MealPlanRecipe avec ratio=1.0
    for meal_plan in MealPlan.objects.filter(recipe__isnull=False):
        MealPlanRecipe.objects.create(
            meal_plan=meal_plan,
            recipe=meal_plan.recipe,
            ratio=1.0,
            order=0
        )


def reverse_migrate(apps, schema_editor):
    """Supprimer les MealPlanRecipe (pas de reverse nécessaire car on garde MealPlan.recipe)"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0031_mealplan_is_cooked_mealplan_mealplan_user_cooked_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealPlanRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratio', models.DecimalField(decimal_places=2, default=1.0, help_text='Ratio à appliquer aux quantités de la recette (défaut: 1.0)', max_digits=5)),
                ('order', models.IntegerField(default=0, help_text="Ordre d'affichage des recettes dans le meal plan")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meal_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plan_recipes', to='recipes.mealplan', verbose_name='Repas planifié')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plan_recipes', to='recipes.recipe', verbose_name='Recette')),
            ],
            options={
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['meal_plan', 'order'], name='mpr_mealplan_order_idx')],
                'unique_together': {('meal_plan', 'recipe')},
            },
        ),
        migrations.RunPython(migrate_existing_meal_plans, reverse_migrate),
    ]
