# Generated by Django 5.2.8 on 2025-11-29 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0032_add_meal_plan_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='guest_count',
            field=models.IntegerField(default=0, help_text="Nombre d'invités anonymes (sans compte) pour ce repas"),
        ),
    ]
