# Generated by Django 5.2.8 on 2025-11-30 10:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0033_add_guest_count_to_mealplan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='mealinvitation',
            index=models.Index(fields=['meal_plan', 'status'], name='mealinv_mealplan_status_idx'),
        ),
        migrations.AddIndex(
            model_name='mealinvitation',
            index=models.Index(fields=['invitee', 'status'], name='mealinv_invitee_status_idx'),
        ),
        migrations.AddIndex(
            model_name='mealinvitation',
            index=models.Index(fields=['meal_plan'], name='mealinv_mealplan_idx'),
        ),
        migrations.AddIndex(
            model_name='mealplan',
            index=models.Index(fields=['user', 'meal_time'], name='mealplan_user_meal_time_idx'),
        ),
        migrations.AddIndex(
            model_name='mealplanrecipe',
            index=models.Index(fields=['meal_plan', 'recipe'], name='mpr_mealplan_recipe_idx'),
        ),
    ]
