# Generated by Django 5.2.8 on 2025-12-03 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0034_add_performance_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MealPlanGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text="Nom optionnel du groupe (ex: 'Repas de la semaine')", max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='Utilisateur propriétaire du groupe', on_delete=django.db.models.deletion.CASCADE, related_name='meal_plan_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Groupe de repas planifiés',
                'verbose_name_plural': 'Groupes de repas planifiés',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MealPlanGroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, help_text="Ordre d'affichage dans le groupe (pour trier par date)")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(help_text='Groupe auquel appartient ce meal plan', on_delete=django.db.models.deletion.CASCADE, related_name='members', to='recipes.mealplangroup')),
                ('meal_plan', models.ForeignKey(help_text='Meal plan membre du groupe', on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='recipes.mealplan')),
            ],
            options={
                'verbose_name': 'Membre de groupe de repas',
                'verbose_name_plural': 'Membres de groupes de repas',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='mealplangroup',
            index=models.Index(fields=['user', '-created_at'], name='mpg_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='mealplangroupmember',
            index=models.Index(fields=['group', 'order'], name='mpgm_group_order_idx'),
        ),
        migrations.AddIndex(
            model_name='mealplangroupmember',
            index=models.Index(fields=['meal_plan'], name='mpgm_mealplan_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mealplangroupmember',
            unique_together={('group', 'meal_plan')},
        ),
    ]
