# Generated by Django 5.2.8 on 2025-12-03 21:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0035_add_meal_plan_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MealPlanRecipeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='Utilisateur propriétaire du groupe', on_delete=django.db.models.deletion.CASCADE, related_name='meal_plan_recipe_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Groupe de recettes planifiées',
                'verbose_name_plural': 'Groupes de recettes planifiées',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MealPlanRecipeGroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, help_text="Ordre d'affichage dans le groupe (pour trier par date)")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(help_text='Groupe auquel appartient cette recette', on_delete=django.db.models.deletion.CASCADE, related_name='members', to='recipes.mealplanrecipegroup')),
                ('meal_plan_recipe', models.ForeignKey(help_text='Recette membre du groupe', on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='recipes.mealplanrecipe')),
            ],
            options={
                'verbose_name': 'Membre de groupe de recette',
                'verbose_name_plural': 'Membres de groupes de recettes',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='mealplanrecipegroup',
            index=models.Index(fields=['user', '-created_at'], name='mprg_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='mealplanrecipegroupmember',
            index=models.Index(fields=['group', 'order'], name='mprgm_group_order_idx'),
        ),
        migrations.AddIndex(
            model_name='mealplanrecipegroupmember',
            index=models.Index(fields=['meal_plan_recipe'], name='mprgm_mpr_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mealplanrecipegroupmember',
            unique_together={('group', 'meal_plan_recipe')},
        ),
    ]
