# Generated by Django 5.2.8 on 2025-12-09 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0036_add_meal_plan_recipe_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='MealPlanGroupMember',
        ),
        migrations.DeleteModel(
            name='MealPlanGroup',
        ),
        migrations.DeleteModel(
            name='MealPlanRecipeGroupMember',
        ),
        migrations.DeleteModel(
            name='MealPlanRecipeGroup',
        ),
        migrations.DeleteModel(
            name='MealPlanRecipe',
        ),
        migrations.CreateModel(
            name='RecipeBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_batches', to=settings.AUTH_USER_MODEL)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='recipes.recipe')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MealPlanRecipeBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratio', models.DecimalField(decimal_places=2, default=1.0, help_text='Ratio appliqué aux quantités (défaut: 1.0)', max_digits=5)),
                ('order', models.IntegerField(default=0, help_text="Ordre d'affichage dans le meal plan")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meal_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plan_recipe_batches', to='recipes.mealplan', verbose_name='Repas planifié')),
                ('recipe_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plan_recipe_batches', to='recipes.recipebatch', verbose_name='Batch')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='recipebatch',
            index=models.Index(fields=['recipe', '-created_at'], name='recipebatch_recipe_idx'),
        ),
        migrations.AddIndex(
            model_name='mealplanrecipebatch',
            index=models.Index(fields=['meal_plan', 'order'], name='mprb_mealplan_order_idx'),
        ),
        migrations.AddIndex(
            model_name='mealplanrecipebatch',
            index=models.Index(fields=['meal_plan', 'recipe_batch'], name='mprb_mealplan_batch_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mealplanrecipebatch',
            unique_together={('meal_plan', 'recipe_batch')},
        ),
    ]
