# Generated by Django 5.2.8 on 2025-12-09 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0037_big_refacto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='step',
            options={'ordering': ['recipe_batch', 'order']},
        ),
        migrations.RemoveConstraint(
            model_name='cookingprogress',
            name='unique_in_progress_per_recipe_mealplan',
        ),
        migrations.RemoveConstraint(
            model_name='postphoto',
            name='unique_photo_type_per_meal_plan',
        ),
        migrations.RemoveIndex(
            model_name='cookingprogress',
            name='cookprog_recipe_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='post_recipe_idx',
        ),
        migrations.RemoveField(
            model_name='cookingprogress',
            name='meal_plan',
        ),
        migrations.RemoveField(
            model_name='cookingprogress',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='post',
            name='cooking_progress',
        ),
        migrations.RemoveField(
            model_name='post',
            name='meal_plan',
        ),
        migrations.RemoveField(
            model_name='post',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='postphoto',
            name='meal_plan',
        ),
        migrations.RemoveField(
            model_name='shoppinglist',
            name='meal_plans',
        ),
        migrations.RemoveField(
            model_name='timer',
            name='recipe',
        ),
        migrations.AddField(
            model_name='cookingprogress',
            name='recipe_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cooking_progresses', to='recipes.recipebatch'),
        ),
        migrations.AddField(
            model_name='post',
            name='recipe_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='recipes.recipebatch'),
        ),
        migrations.AddField(
            model_name='postphoto',
            name='recipe_batch',
            field=models.ForeignKey(blank=True, help_text='Batch associé (avant publication)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='draft_photos', to='recipes.recipebatch'),
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='recipe_batches',
            field=models.ManyToManyField(help_text='Batches inclus dans cette liste', related_name='shopping_lists', to='recipes.recipebatch'),
        ),
        migrations.AddField(
            model_name='step',
            name='recipe_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='recipes.recipebatch'),
        ),
        migrations.AlterUniqueTogether(
            name='step',
            unique_together={('recipe_batch', 'order')},
        ),
        migrations.AddField(
            model_name='timer',
            name='recipe_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='active_timers', to='recipes.recipebatch'),
        ),
        migrations.AddIndex(
            model_name='cookingprogress',
            index=models.Index(fields=['recipe_batch', 'status'], name='cookprog_batch_status_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['recipe_batch'], name='post_recipebatch_idx'),
        ),
        migrations.AddConstraint(
            model_name='cookingprogress',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'in_progress')), fields=('user', 'recipe_batch', 'status'), name='unique_in_progress_per_batch'),
        ),
        migrations.AddConstraint(
            model_name='postphoto',
            constraint=models.UniqueConstraint(condition=models.Q(('photo_type__in', ['during_cooking', 'after_cooking', 'at_meal_time']), ('recipe_batch__isnull', False)), fields=('recipe_batch', 'photo_type'), name='unique_photo_type_per_batch'),
        ),
        migrations.RemoveField(
            model_name='step',
            name='recipe',
        ),
    ]
