# Generated by Django 5.2.8 on 2025-12-09 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0038_batch_only_refactor'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='mealplan',
            name='mealplan_user_cooked_idx',
        ),
        migrations.RemoveField(
            model_name='mealplan',
            name='is_cooked',
        ),
    ]
