# Generated by Django 5.2.8 on 2025-12-09 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0039_remove_mealplan_is_cooked'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipebatch',
            name='is_cooked',
            field=models.BooleanField(default=False, help_text='Au moins un meal plan lié est cuisiné'),
        ),
    ]
