# Generated by Django 5.2.8 on 2026-01-15 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0042_remove_mealplan_recipe'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='postphoto',
            name='unique_photo_type_per_post',
        ),
        migrations.RemoveConstraint(
            model_name='postphoto',
            name='unique_photo_type_per_batch',
        ),
        migrations.AddField(
            model_name='postphoto',
            name='is_draft',
            field=models.BooleanField(default=False, help_text='Photo en cours de capture (pas encore uploadée)'),
        ),
        migrations.AddField(
            model_name='recipebatch',
            name='photo_step_orders',
            field=models.JSONField(blank=True, default=list, help_text='Liste des step.order qui auront des étapes photo (ex: [3, 5])'),
        ),
        migrations.AlterField(
            model_name='postphoto',
            name='image_path',
            field=models.CharField(blank=True, help_text='Chemin relatif de la photo dans S3 (ex: meal_plans/70/6096a520a71247229f1cae315fc2bd84.jpg)', max_length=500),
        ),
        migrations.AddConstraint(
            model_name='postphoto',
            constraint=models.UniqueConstraint(condition=models.Q(('photo_type__in', ['after_cooking', 'at_meal_time']), ('post__isnull', False)), fields=('post', 'photo_type'), name='unique_photo_type_per_post'),
        ),
        migrations.AddConstraint(
            model_name='postphoto',
            constraint=models.UniqueConstraint(condition=models.Q(('photo_type__in', ['after_cooking', 'at_meal_time']), ('recipe_batch__isnull', False)), fields=('recipe_batch', 'photo_type'), name='unique_photo_type_per_batch'),
        ),
    ]
