# Generated by Django 5.2.8 on 2026-01-21 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0043_remove_postphoto_unique_photo_type_per_post_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='postphoto',
            name='unique_photo_type_per_post',
        ),
        migrations.RemoveConstraint(
            model_name='postphoto',
            name='unique_photo_type_per_batch',
        ),
        migrations.AddConstraint(
            model_name='postphoto',
            constraint=models.UniqueConstraint(condition=models.Q(('photo_type', 'at_meal_time'), ('post__isnull', False)), fields=('post', 'photo_type'), name='unique_photo_type_per_post'),
        ),
        migrations.AddConstraint(
            model_name='postphoto',
            constraint=models.UniqueConstraint(condition=models.Q(('photo_type', 'at_meal_time'), ('recipe_batch__isnull', False)), fields=('recipe_batch', 'photo_type'), name='unique_photo_type_per_batch'),
        ),
    ]
