# Generated by GPT on 2026-01-28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0044_remove_postphoto_unique_photo_type_per_post_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # RESET HARD: delete old models (data loss accepted)
        migrations.DeleteModel(
            name='ShoppingListItem',
        ),
        migrations.DeleteModel(
            name='ShoppingList',
        ),

        # Recreate ShoppingList V2
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Nom de la liste (ex: Maison, Appart, etc.)', max_length=200)),
                ('color', models.CharField(blank=True, help_text='Couleur optionnelle (hex ou token)', max_length=20)),
                ('is_archived', models.BooleanField(default=False, help_text='Liste archivée')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),

        migrations.CreateModel(
            name='ShoppingListMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Propriétaire'), ('collaborator', 'Collaborateur')], default='collaborator', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('shopping_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='recipes.shoppinglist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_list_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['joined_at'],
                'unique_together': {('shopping_list', 'user')},
            },
        ),

        migrations.CreateModel(
            name='ShoppingListBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipe_batch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_list_batch', to='recipes.recipebatch')),
                ('shopping_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='recipes.shoppinglist')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),

        migrations.CreateModel(
            name='ShoppingListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_group', models.CharField(choices=[('weight', 'Poids (g/kg)'), ('volume', 'Volume (ml/l)'), ('count', 'Pièce'), ('pinch', 'Pincée'), ('clove', 'Gousse'), ('other', 'Autre')], default='other', help_text="Regroupement d'unité pour permettre plusieurs lignes par ingrédient", max_length=20)),
                ('pantry_quantity', models.DecimalField(decimal_places=2, default=0, help_text='Quantité déjà disponible dans les placards (par ligne)', max_digits=10)),
                ('pantry_unit', models.CharField(blank=True, help_text='Unité de la quantité dans les placards (doit correspondre au groupe d\'unité)', max_length=20)),
                ('checked_at', models.DateTimeField(blank=True, help_text='Dernière validation (ligne)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shopping_list_item_checks', to=settings.AUTH_USER_MODEL)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_list_items', to='recipes.ingredient')),
                ('shopping_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='recipes.shoppinglist')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('shopping_list', 'ingredient', 'unit_group')},
            },
        ),

        migrations.CreateModel(
            name='ShoppingListItemQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('checked_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shopping_list_item_quantity_checks', to=settings.AUTH_USER_MODEL)),
                ('recipe_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_list_item_quantities', to='recipes.recipebatch')),
                ('shopping_list_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantities', to='recipes.shoppinglistitem')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('shopping_list_item', 'recipe_batch')},
            },
        ),

        migrations.CreateModel(
            name='ShoppingListInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Acceptée'), ('declined', 'Refusée')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_shopping_list_invitations', to=settings.AUTH_USER_MODEL)),
                ('invitee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_shopping_list_invitations', to=settings.AUTH_USER_MODEL)),
                ('shopping_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='recipes.shoppinglist')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('invitee', 'shopping_list')},
            },
        ),

        migrations.AddIndex(
            model_name='shoppinglistmember',
            index=models.Index(fields=['shopping_list', 'role'], name='shoplistmember_role_idx'),
        ),
        migrations.AddIndex(
            model_name='shoppinglistbatch',
            index=models.Index(fields=['shopping_list', 'created_at'], name='shoplistbatch_list_created_idx'),
        ),
        migrations.AddIndex(
            model_name='shoppinglistitem',
            index=models.Index(fields=['shopping_list', 'unit_group'], name='shoplistitem_group_idx'),
        ),
        migrations.AddIndex(
            model_name='shoppinglistitem',
            index=models.Index(fields=['shopping_list', 'checked_at'], name='shoplistitem_checked_idx'),
        ),
        migrations.AddIndex(
            model_name='shoppinglistitemquantity',
            index=models.Index(fields=['recipe_batch', 'updated_at'], name='shopliq_batch_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='shoppinglistinvitation',
            index=models.Index(fields=['shopping_list', 'status'], name='shoplistinv_list_status_idx'),
        ),
    ]


