# Generated by Django 5.2.8 on 2026-02-20 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0046_shoppinglistitemquantity_recipe_batch_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipebatch',
            name='shopping_done',
            field=models.BooleanField(default=False, help_text="Courses terminées pour ce batch (soit utilisateur a tout coché, soit a choisi « J'ai déjà fait les courses »)"),
        ),
    ]
