# Generated by Django 5.2.8 on 2026-03-29 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0059_preference_mappings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferencemapping',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userpreferencemapping',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
