# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0061_postphoto_uploaded_by_remove_at_meal_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipebatch',
            name='meal_time_photo_reminder_task_id',
            field=models.CharField(
                blank=True,
                default='',
                help_text='ID tâche Celery (rappel push photo à table) pour révocation si replanification',
                max_length=255,
            ),
        ),
    ]
