# Generated by Django 5.2.8

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0067_post_cooking_time_minutes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostRepost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('host_user', models.ForeignKey(help_text='Auteur du post original (hôte du repas).', on_delete=django.db.models.deletion.CASCADE, related_name='hosted_post_reposts', to=settings.AUTH_USER_MODEL)),
                ('original_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reposts', to='recipes.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_reposts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='postrepost',
            index=models.Index(fields=['original_post', 'created_at'], name='postrepost_post_created_idx'),
        ),
        migrations.AddIndex(
            model_name='postrepost',
            index=models.Index(fields=['user', 'created_at'], name='postrepost_user_created_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='postrepost',
            unique_together={('user', 'original_post')},
        ),
    ]
