# Generated by Django 5.2.8 on 2026-08-11 21:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0069_mealplan_dining_alone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='postphoto',
            index=models.Index(fields=['meal_plan', 'is_draft', '-created_at'], name='postphoto_mealplan_temp_idx'),
        ),
    ]
